DEFAULT_LINKED_LIST_THRESHOLD = 10
DIRECT_METADATA_MAX_BYTES = 900
DEFAULT_WRITE_FEE_RECEIVER = "EWNSTD8tikwqHMcRNuuNbZrnYJUiJdKq9UXLXSEU4wZ1"
DEFAULT_IQ_MINT = "4mxHqXJfcydM6iDF4aFoG1R9YFxqiJ3B6HZBHjUxx7uX"  # testmint
